apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/appinfo/prometheus'
  name: {appName}
  namespace: {namespace}
  labels:
    app: {appName}
spec:
  ports:
  - name: {appName}
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: {appName}